# -*- coding: utf-8 -*-

# 服务器组件类型定义
UNKNOWN_COMPONENT_TYPE	= 0
DBMGR_TYPE				= 1
LOGINAPP_TYPE			= 2
BASEAPPMGR_TYPE			= 3
CELLAPPMGR_TYPE			= 4
CELLAPP_TYPE			= 5
BASEAPP_TYPE			= 6
CLIENT_TYPE				= 7
MACHINE_TYPE			= 8
CONSOLE_TYPE			= 9
LOGGER_TYPE				= 10
BOTS_TYPE				= 11
WATCHER_TYPE			= 12
INTERFACES_TYPE			= 13
COMPONENT_END_TYPE		= 14
