LIB =	g3dlite

SRCS =				\
	AABox			\
	Box			\
	Crypto			\
	format			\
	Matrix3			\
	Plane			\
	System			\
	Triangle		\
	Vector3			\
	Vector4

ifndef KBE_ROOT
export KBE_ROOT := $(subst /kbe/src/lib/dependencies/$(LIB),,$(CURDIR))
endif

include $(KBE_ROOT)/kbe/src/build/common.mak