.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_COLLECTION_SET_READ_CONCERN" "3" "2016\(hy03\(hy16" "MongoDB C Driver"
.SH NAME
mongoc_collection_set_read_concern() \- Sets the read concern to use for operations on collection.
.SH "SYNOPSIS"

.nf
.nf
void
mongoc_collection_set_read_concern (mongoc_collection_t          *collection,
                                    const mongoc_read_concern_t  *read_concern);
.fi
.fi

.SH "PARAMETERS"

.TP
.B
collection
A
.B mongoc_collection_t
\e&.
.LP
.TP
.B
read_concern
A
.B mongoc_read_concern_t
\e&.
.LP

.SH "DESCRIPTION"

Sets the read concern to use for operations on
.B collection
\e&.

The default read concern is empty: No readConcern is sent to the server unless explicitly configured.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.