.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_GRIDFS_FILE_SAVE" "3" "2016\(hy03\(hy16" "MongoDB C Driver"
.SH NAME
mongoc_gridfs_file_save() \- Saves modifications to file to the MongoDB server.
.SH "SYNOPSIS"

.nf
.nf
bool
mongoc_gridfs_file_save (mongoc_gridfs_file_t *file);
.fi
.fi

.SH "PARAMETERS"

.TP
.B
file
A
.B mongoc_gridfs_file_t
\e&.
.LP

.SH "DESCRIPTION"

Saves modifications to
.B file
to the MongoDB server.

If an error occurred, false is returned and the error can be retrieved with
.B mongoc_gridfs_file_error(3)
\e&.

.SH "RETURNS"

Returns true if successful, otherwise false.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.