.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_RAND_SEED" "3" "2015\(hy09\(hy21" "MongoDB C Driver"
.SH NAME
mongoc_rand_seed() \- Seeds the mongoc random number generator with num bytes of entropy.
.SH "SYNOPSIS"

.nf
.nf
void
mongoc_rand_seed(const void *buf,
                 int         num);
.fi
.fi

.SH "DESCRIPTION"

Seeds the mongoc random number generator with num bytes of entropy.

.SH "PARAMETERS"

.TP
.B
buf
A buffer.
.LP
.TP
.B
num
An int of number of bytes in buf.
.LP


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.