.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_URI_GET_READ_PREFS_T" "3" "2016\(hy03\(hy30" "MongoDB C Driver"
.SH NAME
mongoc_uri_get_read_prefs_t() \- Fetches a read preference that is owned by the URI instance. This read preference concern is configured based on URI parameters.
.SH "SYNOPSIS"

.nf
.nf
const mongoc_read_prefs_t *
mongoc_uri_get_read_prefs_t (const mongoc_uri_t *uri);
.fi
.fi

.SH "PARAMETERS"

.TP
.B
uri
A
.B mongoc_uri_t
\e&.
.LP

.SH "DESCRIPTION"

Fetches a read preference that is owned by the URI instance. This read preference concern is configured based on URI parameters.

.SH "RETURNS"

Returns a
.B mongoc_read_prefs_t
that should not be modified or freed.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.