.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_DATABASE_REMOVE_USER" "3" "2016\(hy03\(hy16" "MongoDB C Driver"
.SH NAME
mongoc_database_remove_user() \- None
.SH "SYNOPSIS"

.nf
.nf
bool
mongoc_database_remove_user (mongoc_database_t *database,
                             const char        *username,
                             bson_error_t      *error);
.fi
.fi

This function removes the user named
.B username
from
.B database
\e&.

.SH "PARAMETERS"

.TP
.B
database
A
.B mongoc_database_t
\e&.
.LP
.TP
.B
username
A string containing the username of the user to remove.
.LP
.TP
.B
error
An optional location for a
.B bson_error_t
or
.B NULL
\e&.
.LP

.SH "ERRORS"

Errors are propagated via the
.B error
parameter. This could include socket errors or others if the current user is not authorized to perform the command.

.SH "RETURNS"

.B true
on success, otherwise
.B false
and
.B error
is set.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.