.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_SOCKET_ACCEPT" "3" "2016\(hy03\(hy16" "MongoDB C Driver"
.SH NAME
mongoc_socket_accept() \- This function is a wrapper around the BSD socket accept() interface. It allows for more portability between UNIX-like and Microsoft Windows platforms.
.SH "SYNOPSIS"

.nf
.nf
mongoc_socket_t *
mongoc_socket_accept (mongoc_socket_t *sock,
                      int64_t          expire_at);
.fi
.fi

.SH "PARAMETERS"

.TP
.B
sock
A
.B mongoc_socket_t
\e&.
.LP
.TP
.B
expire_at
An int64_t containing a timeout in milliseconds.
.LP

.SH "DESCRIPTION"

This function is a wrapper around the BSD socket
.B accept(3)
interface. It allows for more portability between UNIX\(hylike and Microsoft Windows platforms.

.SH "RETURNS"

NULL upon failure to accept or timeout. A newly allocated
.B mongoc_socket_t
that should be released with
.B mongoc_socket_destroy(3)
on success.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.