.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_GRIDFS_DESTROY" "3" "2016\(hy03\(hy16" "MongoDB C Driver"
.SH NAME
mongoc_gridfs_destroy() \- This function shall destroy the gridfs structure referenced by gridfs and any resources associated with the gridfs.
.SH "SYNOPSIS"

.nf
.nf
void
mongoc_gridfs_destroy (mongoc_gridfs_t *gridfs);
.fi
.fi

.SH "PARAMETERS"

.TP
.B
gridfs
A
.B mongoc_gridfs_t
\e&.
.LP

.SH "DESCRIPTION"

This function shall destroy the gridfs structure referenced by
.B gridfs
and any resources associated with the gridfs.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.