.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_WRITE_CONCERN_SET_FSYNC" "3" "2016\(hy03\(hy16" "MongoDB C Driver"
.SH NAME
mongoc_write_concern_set_fsync() \- Sets if a fsync must be performed before indicating write success.
.SH "SYNOPSIS"

.nf
.nf
void
mongoc_write_concern_set_fsync (mongoc_write_concern_t *write_concern,
                                bool                    fsync_);
.fi
.fi

.SH "PARAMETERS"

.TP
.B
write_concern
A
.B mongoc_write_concern_t
\e&.
.LP
.TP
.B
fsync_
A boolean.
.LP

.SH "DESCRIPTION"

Sets if a fsync must be performed before indicating write success.

.SH "DEPRECATED"

.B NOTE
.RS
The
.B fsync
write concern is deprecated.
.RE

Please use
.B mongoc_write_concern_set_journal(3)
instead.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.