.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_DATABASE_COMMAND_SIMPLE" "3" "2016\(hy03\(hy16" "MongoDB C Driver"
.SH NAME
mongoc_database_command_simple() \- This is a simplified interface to mongoc_database_command() that returns the first result document.
.SH "SYNOPSIS"

.nf
.nf
bool
mongoc_database_command_simple (mongoc_database_t         *database,
                                const bson_t              *command,
                                const mongoc_read_prefs_t *read_prefs,
                                bson_t                    *reply,
                                bson_error_t              *error);
.fi
.fi

.SH "PARAMETERS"

.TP
.B
database
A
.B mongoc_database_t
\e&.
.LP
.TP
.B
command
A
.B bson_t
containing the command.
.LP
.TP
.B
read_prefs
An optional
.B mongoc_read_prefs_t
\e&.
.LP
.TP
.B
reply
A location to store the commands first result document.
.LP
.TP
.B
error
An optional location for a
.B bson_error_t
or
.B NULL
\e&.
.LP

This is a simplified interface to
.B mongoc_database_command(3)
that returns the first result document.

.B NOTE
.RS
This function will
.B always
initialize
.B reply
\e&. The caller should always call
.B bson_destroy(3)
with
.B reply
as an argument.
.RE

.SH "ERRORS"

Errors are propagated through the
.B error
parameter.

.SH "RETURNS"

.B true
on success,
.B false
on failure and
.B error
is set.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.