.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_GRIDFS_FILE_OPT_T" "3" "2016\(hy03\(hy16" "MongoDB C Driver"
.SH NAME
mongoc_gridfs_file_opt_t \- This structure contains options that can be set on a mongoc_gridfs_file_t. It can be used by various functions when creating a new gridfs file.
.SH "SYNOPSIS"

.nf
typedef struct
{
   const char   *md5;
   const char   *filename;
   const char   *content_type;
   const bson_t *aliases;
   const bson_t *metadata;
   uint32_t      chunk_size;
} mongoc_gridfs_file_opt_t;
.fi

.SH "DESCRIPTION"

This structure contains options that can be set on a
.B mongoc_gridfs_file_t
\e&. It can be used by various functions when creating a new gridfs file.


.B
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.