.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "BSON_CHECK_VERSION" "3" "2016\(hy03\(hy16" "libbson"
.SH NAME
bson_check_version() \- Check at runtime if this release of libbson meets a required version.
.SH "SYNOPSIS"

.nf
.nf
bool
bson_check_version (int required_major,
                    int required_minor,
                    int required_micro);
.fi
.fi

.SH "PARAMETERS"

.TP
.B
required_major
The minimum major version required.
.LP
.TP
.B
required_minor
The minimum minor version required.
.LP
.TP
.B
required_micro
The minimum micro version required.
.LP

.SH "DESCRIPTION"

Check at runtime if this release of libbson meets a required version.

.SH "RETURNS"

True if libbson's version is greater than or equal to the required version.


.B
.SH COLOPHON
This page is part of libbson.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.