.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "BSON_ITER_DBPOINTER" "3" "2016\(hy03\(hy16" "libbson"
.SH NAME
bson_iter_dbpointer() \- Fetches the contents of a BSON_TYPE_DBPOINTER element.
.SH "SYNOPSIS"

.nf
.nf
void
bson_iter_dbpointer (const bson_iter_t *iter,
                     uint32_t          *collection_len,
                     const char       **collection,
                     const bson_oid_t **oid);
.fi
.fi

.SH "PARAMETERS"

.TP
.B
iter
A
.B bson_iter_t
\e&.
.LP
.TP
.B
collection_len
A location for the length of the collection name.
.LP
.TP
.B
collection
A location for the collection name..
.LP
.TP
.B
oid
A location for a
.B bson_oid_t
\e&.
.LP

.SH "DESCRIPTION"

Fetches the contents of a BSON_TYPE_DBPOINTER element.

.B NOTE
.RS
The BSON_TYPE_DBPOINTER field type is deprecated by the BSON spec and should not be used in new code.
.RE


.B
.SH COLOPHON
This page is part of libbson.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.