.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "BSON_COMPARE" "3" "2016\(hy03\(hy16" "libbson"
.SH NAME
bson_compare() \- The bson_compare() function shall compare two bson documents for equality.
.SH "SYNOPSIS"

.nf
.nf
int
bson_compare (const bson_t *bson,
              const bson_t *other);
.fi
.fi

.SH "PARAMETERS"

.TP
.B
bson
A
.B bson_t
\e&.
.LP
.TP
.B
other
A
.B bson_t
\e&.
.LP

.SH "DESCRIPTION"

The
.B bson_compare(3)
function shall compare two bson documents for equality.

This can be useful in conjunction with _qsort()_.

If equal, 0 is returned.

.B NOTE
.RS
This function uses _memcmp()_ internally, so the semantics are the same.
.RE

.SH "RETURNS"

less than zero, zero, or greater than zero in
.B qsort(3)
style.


.B
.SH COLOPHON
This page is part of libbson.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.