.\" This manpage is Copyright (C) 2016 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "BSON_GET_MINOR_VERSION" "3" "2016\(hy03\(hy16" "libbson"
.SH NAME
bson_get_minor_version() \- Get the middle number in libbson's MAJOR.MINOR.MICRO release version.
.SH "SYNOPSIS"

.nf
.nf
int
bson_get_minor_version (void);
.fi
.fi

.SH "DESCRIPTION"

Get the middle number in libbson's MAJOR.MINOR.MICRO release version.

.SH "RETURNS"

The value of
.B BSON_MINOR_VERSION
when Libbson was compiled.


.B
.SH COLOPHON
This page is part of libbson.
Please report any bugs at https://jira.mongodb.org/browse/CDRIVER.